apply-url: wget by default, check https support if needed

diff --git a/git-apply-url b/git-apply-url
--- a/git-apply-url
+++ b/git-apply-url
@@ -39,12 +39,17 @@ dir=$(git rev-parse --git-dir 2>/dev/null)
 
 [ $# -ne 1 ] && usage
 
-if [ -x "$(which curl)" ] && [ -n "$(curl -V | grep https)" ] ; then
-    cmd="curl -s"
-elif [ -x "$(which wget)" ] ; then
+https=$(echo "$1" | egrep "^https://")
+
+if [ -x "$(which wget)" ] ; then
     cmd="wget -O - -q --no-check-certificate"
+elif [ -x "$(which curl)" ] ; then
+    if [ -n "$https" ] && [ -z "$(curl -V | grep https)" ] ; then
+        echo "git-apply-url: your curl version does not support https" >&2 && exit 1
+    fi
+    cmd="curl -s"
 else
-    echo "git-apply-url: could not found curl with https support nor wget" >&2 && exit 1
+    echo "git-apply-url: could not found wget nor curl" >&2 && exit 1
 fi
 
 $cmd "$1" | patch -p1
